

export const PRODUCTOS_DESTACADOS = [
  {
    id: 1,
    nombre: 'Televisor LG OLED 55" 4K Smart TV AI ThinQ',
    descripcion: 'Procesador α9 Gen6 - 120Hz Refresh Rate - Dolby Vision / Atmos',
    estado: 'nuevo',
    categoria: 'Televisores',
    marca: 'LG',
    precio: 3899999,
    pulgadas: 55,
    panel: 'OLED',
    resolucion: '4K UHD',
    sistema: 'webOS',
    refresco: '120Hz',
    calificacion: 4.8,
    envioRapido: true,
    descuento: 15,
    blackFriday: true,
    vendedor: { id: 1, nombre: 'LG Store Oficial', reputacion: 4.8 },
    imagen: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=800'
  },
  {
    id: 2,
    nombre: 'Laptop Lenovo IdeaPad Slim 5 16" AMD Ryzen 7',
    descripcion: 'Almacenamiento: 512GB SSD - RAM: 16GB DDR5 - Pantalla FHD+',
    estado: 'nuevo',
    categoria: 'Laptops',
    marca: 'Lenovo',
    precio: 2899999,
    ram: '16GB',
    almacenamiento: '512GB',
    almacenamientoTipo: 'SSD NVMe',
    pulgadas: '16"',
    cpu: 'AMD Ryzen 7',
    gpu: 'Integrada',
    uso: 'Oficina',
    calificacion: 4.4,
    envioRapido: true,
    descuento: 20,
    blackFriday: true,
    vendedor: { id: 2, nombre: 'Lenovo Colombia', reputacion: 4.6 },
    imagen: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=800'
  },
  {
    id: 3,
    nombre: 'iPhone 15 Pro Max 256GB Titanio Natural',
    descripcion: 'Pantalla Super Retina XDR 6.7" - Chip A17 Pro - Cámara 48MP',
    estado: 'reacondicionado',
    categoria: 'Celulares',
    marca: 'Apple',
    precio: 4999999,
    ram: '8GB',
    almacenamiento: '256GB',
    so: 'iOS',
    pulgadas: 6.7,
    camara: '48MP',
    calificacion: 4.9,
    envioRapido: true,
    descuento: 10,
    blackFriday: true,
    vendedor: { id: 3, nombre: 'Charlie Kirk', reputacion: 4.3, avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Charlie_Kirk_%2849271286182%29_%28cropped%29.jpg/960px-Charlie_Kirk_%2849271286182%29_%28cropped%29.jpg' },
    imagen: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=800'
  }
]


export const PRODUCTOS_PERFIL = [
  {
    id: 4,
    titulo: 'Xiaomi Redmi 13C 4GB-64GB - Negro',
    ram: '4GB',
    almacenamiento: '64GB',
    so: 'Android',
    pulgadas: 6.74,
    camara: '50MP',
    calificacion: 4.1,
    stock: false,
    precio: 1085999,
    precioAnterior: 1299999,
    imagen: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=600',
    descripcion: 'Pantalla HD+ de 6.74", 4GB de RAM, 64GB de almacenamiento y batería de 5000mAh.',
    estado: 'usado',
    categoria: 'Celulares',
    marca: 'Xiaomi',
    vendedor: { id: 4, nombre: 'Luis Alejandro Montenegro Ojeda', reputacion: 4.7 }
  },
  {
    id: 5,
    titulo: 'Xiaomi Redmi Note 13 Pro 8GB-256GB - Azul',
    ram: '8GB',
    almacenamiento: '256GB',
    so: 'Android',
    pulgadas: 6.67,
    camara: '208MP',
    calificacion: 4.6,
    precio: 1085999,
    precioAnterior: 1399999,
    imagen: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?q=80&w=600',
    descripcion: 'Pantalla AMOLED 120Hz, 8GB de RAM, 256GB de almacenamiento y cámara de 200MP.',
    estado: 'nuevo',
    categoria: 'Celulares',
    marca: 'Xiaomi',
    vendedor: { id: 4, nombre: 'Luis Alejandro Montenegro Ojeda', reputacion: 4.7 }
  },
  {
    id: 6,
    titulo: 'Xiaomi Redmi 12 5G 8GB-256GB - Verde',
    ram: '8GB',
    almacenamiento: '256GB',
    so: 'Android',
    pulgadas: 6.79,
    camara: '108MP',
    calificacion: 4.3,
    precio: 1085999,
    precioAnterior: 1259999,
    imagen: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=600',
    descripcion: 'Pantalla FHD+ 120Hz, 8GB de RAM, 256GB de almacenamiento y conexión 5G.',
    estado: 'usado',
    categoria: 'Celulares',
    marca: 'Xiaomi',
    vendedor: { id: 4, nombre: 'Luis Alejandro Montenegro Ojeda', reputacion: 4.7 }
  },
  {
    id: 7,
    titulo: 'Xiaomi Poco X6 8GB-256GB - Blanco',
    ram: '8GB',
    almacenamiento: '256GB',
    so: 'Android',
    pulgadas: 6.67,
    camara: '64MP',
    calificacion: 4.5,
    precio: 1085999,
    precioAnterior: 1499999,
    imagen: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?q=80&w=600',
    descripcion: 'Pantalla AMOLED 120Hz, 8GB de RAM, 256GB de almacenamiento y carga rápida de 67W.',
    estado: 'nuevo',
    categoria: 'Celulares',
    marca: 'POCO',
    vendedor: { id: 4, nombre: 'Luis Alejandro Montenegro Ojeda', reputacion: 4.7 }
  },
  {
    id: 8,
    titulo: 'Xiaomi Redmi Note 12 6GB-128GB - Gris',
    ram: '6GB',
    almacenamiento: '128GB',
    so: 'Android',
    pulgadas: 6.67,
    camara: '108MP',
    calificacion: 3.9,
    stock: false,
    precio: 1085999,
    precioAnterior: 1199999,
    imagen: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?q=80&w=600',
    descripcion: 'Pantalla AMOLED 90Hz, 6GB de RAM, 128GB de almacenamiento y batería de 5000mAh.',
    estado: 'usado',
    categoria: 'Celulares',
    marca: 'Xiaomi',
    vendedor: { id: 4, nombre: 'Luis Alejandro Montenegro Ojeda', reputacion: 4.7 }
  }
]


export const PRODUCTOS_PROMOCION = [
  {
    id: 9,
    nombre: 'Tarjeta Gráfica NVIDIA GeForce RTX 4070 Ti SUPER 12GB',
    descripcion: '12GB GDDR6X | Arquitectura Ada Lovelace | DLSS 3 y Ray Tracing',
    estado: 'nuevo',
    categoria: 'Componentes PC',
    marca: 'NVIDIA',
    gaming: true,
    precio: 3499999,
    vram: '12GB',
    calificacion: 4.8,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: '/rtx-4070.jpg'
  },
  {
    id: 10,
    nombre: 'Portátil HP Victus Gaming',
    descripcion: 'Procesador Intel Core i5 | 16GB RAM | 512GB SSD | Gráficos NVIDIA RTX',
    estado: 'nuevo',
    categoria: 'Laptops',
    marca: 'HP',
    gaming: true,
    precio: 1899900,
    ram: '16GB',
    almacenamiento: '512GB',
    almacenamientoTipo: 'SSD NVMe',
    pulgadas: '15.6"',
    cpu: 'Intel Core i5',
    gpu: 'Dedicada',
    uso: 'Gaming',
    calificacion: 4.6,
    envioRapido: true,
    vendedor: { id: 6, nombre: 'HP Store Oficial', reputacion: 4.5 },
    imagen: '/hp-victus.jpg'
  },
  {
    id: 11,
    nombre: 'Monitor LG UltraGear 27" QHD 165Hz Gaming',
    descripcion: 'Panel IPS QHD - 165Hz - Compatible G-Sync - HDR10',
    estado: 'nuevo',
    categoria: 'Componentes PC',
    marca: 'LG',
    gaming: true,
    blackFriday: true,
    precio: 1299999,
    pulgadas: '27"',
    calificacion: 4.6,
    envioRapido: true,
    descuento: 24,
    precioAnterior: 1699999,
    vendedor: { id: 1, nombre: 'LG Store Oficial', reputacion: 4.8 },
    imagen: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800'
  },
  {
    id: 12,
    nombre: 'Laptop Lenovo LOQ 15 Gaming RTX 4060',
    descripcion: 'Procesador Intel Core i5 - 16GB RAM - 512GB SSD - Pantalla 144Hz',
    estado: 'nuevo',
    categoria: 'Laptops',
    marca: 'Lenovo',
    gaming: true,
    blackFriday: true,
    precio: 2799999,
    ram: '16GB',
    almacenamiento: '512GB',
    almacenamientoTipo: 'SSD NVMe',
    pulgadas: '15"',
    cpu: 'Intel Core i7',
    gpu: 'Dedicada',
    uso: 'Gaming',
    calificacion: 4.5,
    envioRapido: true,
    descuento: 22,
    precioAnterior: 3599999,
    vendedor: { id: 2, nombre: 'Lenovo Colombia', reputacion: 4.6 },
    imagen: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800'
  },
  {
    id: 13,
    nombre: 'Teclado Mecánico HP Pavilion 150 RGB',
    descripcion: 'Switches rojos - Retroiluminación RGB - Resistente al derrame',
    estado: 'nuevo',
    categoria: 'Periféricos',
    marca: 'HP',
    blackFriday: true,
    precio: 254999,
    tipo: 'Teclado',
    conectividad: 'Alámbrico',
    iluminacion: 'RGB Estático',
    switch: 'Mecánico Red',
    calificacion: 4.3,
    envioRapido: true,
    descuento: 25,
    precioAnterior: 339999,
    vendedor: { id: 6, nombre: 'HP Store Oficial', reputacion: 4.5 },
    imagen: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800'
  },
  {
    id: 14,
    nombre: 'Smart TV Samsung Crystal 43" 4K UHD',
    descripcion: 'Pantalla LED - Sistema Tizen - 60Hz - HDR10+',
    estado: 'nuevo',
    categoria: 'Televisores',
    marca: 'Samsung',
    precio: 1299999,
    pulgadas: 43,
    resolucion: '4K UHD',
    panel: 'LED',
    sistema: 'Tizen',
    refresco: '60Hz',
    calificacion: 4.5,
    envioRapido: true,
    vendedor: { id: 7, nombre: 'Samsung Store Oficial', reputacion: 4.7 },
    imagen: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?q=80&w=800'
  },
  {
    id: 15,
    nombre: 'Smart TV LG QNED 65" 8K MiniLED',
    descripcion: 'Panel MiniLED - Sistema webOS - 120Hz - Dolby Vision IQ',
    estado: 'nuevo',
    categoria: 'Televisores',
    marca: 'LG',
    precio: 8999999,
    pulgadas: 65,
    resolucion: '8K',
    panel: 'MiniLED',
    sistema: 'webOS',
    refresco: '120Hz',
    calificacion: 4.7,
    envioRapido: true,
    vendedor: { id: 1, nombre: 'LG Store Oficial', reputacion: 4.8 },
    imagen: 'https://images.unsplash.com/photo-1552975084-6e027cd345c2?q=80&w=800'
  },
  {
    id: 16,
    nombre: 'Mouse Gamer Logitech G502 Hero',
    descripcion: 'Sensor 25.600 DPI - 11 botones programables - Iluminación RGB',
    estado: 'nuevo',
    categoria: 'Periféricos',
    marca: 'Logitech',
    gaming: true,
    precio: 349990,
    tipo: 'Mouse',
    conectividad: 'Alámbrico',
    iluminacion: 'RGB Personalizable',
    uso: 'Gaming',
    calificacion: 4.7,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1613141411244-0e4ac259d217?q=80&w=800'
  },
  {
    id: 17,
    nombre: 'Diadema Gamer HyperX Cloud Stinger 2',
    descripcion: 'Audio virtual 7.1 - Micrófono direccional - Conexión Bluetooth',
    estado: 'nuevo',
    categoria: 'Periféricos',
    marca: 'HyperX',
    gaming: true,
    precio: 289990,
    tipo: 'Diadema',
    conectividad: 'Inalámbrico',
    iluminacion: 'Sin RGB',
    uso: 'Gaming',
    calificacion: 4.4,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800'
  },
  {
    id: 18,
    nombre: 'Memoria RAM Corsair Vengeance RGB 16GB DDR5 5600MHz',
    descripcion: 'Kit 2x 8GB - DDR5 - Iluminación RGB - Ideal para gaming',
    estado: 'nuevo',
    categoria: 'Componentes PC',
    marca: 'Corsair',
    gaming: true,
    blackFriday: true,
    precio: 349999,
    tipo: 'Memoria RAM',
    ram: '16GB DDR5 5600MHz',
    iluminacion: 'RGB',
    uso: 'Gaming',
    descuento: 20,
    precioAnterior: 439999,
    calificacion: 4.7,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1540928349545-1baf2ae1ecbe?q=80&w=800'
  },
  {
    id: 19,
    nombre: 'Memoria RAM Kingston Fury Beast 32GB DDR4 3200MHz',
    descripcion: 'Kit 2x 16GB - DDR4 - Perfil XMP - Módulos negros',
    estado: 'nuevo',
    categoria: 'Componentes PC',
    marca: 'Kingston',
    blackFriday: true,
    precio: 429999,
    tipo: 'Memoria RAM',
    ram: '32GB DDR4 3200MHz',
    descuento: 15,
    precioAnterior: 505881,
    calificacion: 4.6,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1676554565685-3aeb5d7ad1b7?q=80&w=800'
  },
  {
    id: 20,
    nombre: 'Teclado Mecánico Redragon K552 RGB',
    descripcion: 'Switches azules - Retroiluminación RGB - Diseño compacto TKL',
    estado: 'nuevo',
    categoria: 'Periféricos',
    marca: 'Redragon',
    gaming: true,
    blackFriday: true,
    precio: 189999,
    tipo: 'Teclado',
    conectividad: 'Alámbrico',
    iluminacion: 'RGB Personalizable',
    switch: 'Mecánico Azul',
    calificacion: 4.5,
    envioRapido: true,
    descuento: 18,
    precioAnterior: 229999,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1771521971801-b24e291166d1?q=80&w=800'
  }
]


export const PRODUCTOS_NOVEDADES = [
  {
    id: 21,
    nombre: 'Smartwatch Apple Watch SE 2ª Gen 40mm',
    descripcion: 'Pantalla Retina Always-On - Resistencia al agua - Seguimiento deportivo',
    estado: 'nuevo',
    categoria: 'Wearables',
    marca: 'Apple',
    precio: 999990,
    precioAnterior: 1199990,
    descuento: 17,
    calificacion: 4.7,
    envioRapido: true,
    vendedor: { id: 3, nombre: 'Charlie Kirk', reputacion: 4.3 },
    imagen: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=800'
  },
  {
    id: 22,
    nombre: 'Pulsera de actividad Xiaomi Smart Band 9',
    descripcion: 'Pantalla AMOLED 1.62" - Batería de 21 días - Más de 150 modos deportivos',
    estado: 'nuevo',
    categoria: 'Wearables',
    marca: 'Xiaomi',
    precio: 149990,
    calificacion: 4.5,
    envioRapido: true,
    vendedor: { id: 4, nombre: 'Luis Alejandro Montenegro Ojeda', reputacion: 4.7 },
    imagen: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?q=80&w=800'
  },
  {
    id: 23,
    nombre: 'Altavoz inteligente Amazon Echo 4ª Gen',
    descripcion: 'Audio de 360° - Alexa integrada - Control del hogar inteligente',
    estado: 'nuevo',
    categoria: 'Smart Home',
    marca: 'Amazon',
    precio: 289990,
    precioAnterior: 349990,
    descuento: 17,
    calificacion: 4.7,
    envioRapido: true,
    vendedor: { id: 7, nombre: 'Samsung Store Oficial', reputacion: 4.7 },
    imagen: 'https://images.unsplash.com/photo-1550985543-49bee3167284?q=80&w=800'
  },
  {
    id: 24,
    nombre: 'Cámara de vigilancia Wi-Fi TP-Link Tapo C200',
    descripcion: 'Resolución 2K - Visión nocturna - Rotación 360° - Audio bidireccional',
    estado: 'nuevo',
    categoria: 'Smart Home',
    marca: 'TP-Link',
    precio: 179990,
    calificacion: 4.4,
    envioRapido: true,
    vendedor: { id: 7, nombre: 'Samsung Store Oficial', reputacion: 4.7 },
    imagen: 'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=800'
  },
  {
    id: 25,
    nombre: 'Focos inteligentes LED RGB Tuya (Pack 4)',
    descripcion: 'Millones de colores - Control por voz - Compatible con Alexa y Google Home',
    estado: 'nuevo',
    categoria: 'Smart Home',
    marca: 'Tuya',
    precio: 119990,
    precioAnterior: 149990,
    descuento: 20,
    calificacion: 4.3,
    envioRapido: true,
    vendedor: { id: 6, nombre: 'HP Store Oficial', reputacion: 4.5 },
    imagen: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?q=80&w=800'
  },
  {
    id: 26,
    nombre: 'Audífonos inalámbricos Sony WH-1000XM5',
    descripcion: 'Cancelación de ruido - 30 horas de batería - Audio Hi-Res',
    estado: 'nuevo',
    categoria: 'Audio',
    marca: 'Sony',
    precio: 1499990,
    precioAnterior: 1799990,
    descuento: 17,
    calificacion: 4.9,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1543512214-318c7553f230?q=80&w=800'
  },
  {
    id: 27,
    nombre: 'Bocina portátil JBL Flip 6 Bluetooth',
    descripcion: 'Resistencia IP67 - 12 horas de reproducción - JBL PartyBoost',
    estado: 'nuevo',
    categoria: 'Audio',
    marca: 'JBL',
    precio: 549990,
    calificacion: 4.7,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?q=80&w=800'
  },
  {
    id: 28,
    nombre: 'Router Wi-Fi 6 TP-Link Archer AX23',
    descripcion: 'Doble banda AX1800 - 4 antenas - Control desde la app Tether',
    estado: 'nuevo',
    categoria: 'Oficina y Conectividad',
    marca: 'TP-Link',
    precio: 349990,
    calificacion: 4.5,
    envioRapido: true,
    vendedor: { id: 6, nombre: 'HP Store Oficial', reputacion: 4.5 },
    imagen: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=800'
  },
  {
    id: 29,
    nombre: 'Impresora multifuncional HP Smart Tank 580',
    descripcion: 'Impresión a color - Tinta continua - Wi-Fi - Escáner incluido',
    estado: 'nuevo',
    categoria: 'Oficina y Conectividad',
    marca: 'HP',
    precio: 899990,
    precioAnterior: 999990,
    descuento: 10,
    calificacion: 4.4,
    envioRapido: true,
    vendedor: { id: 6, nombre: 'HP Store Oficial', reputacion: 4.5 },
    imagen: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?q=80&w=800'
  },
  {
    id: 30,
    nombre: 'Drone DJI Mini 4K con cámara',
    descripcion: 'Cámara 4K - 31 minutos de vuelo - 10 km de alcance - Peso 249g',
    estado: 'nuevo',
    categoria: 'Foto y Video',
    marca: 'DJI',
    precio: 1299999,
    calificacion: 4.8,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?q=80&w=800'
  },
  {
    id: 31,
    nombre: 'Consola PlayStation 5 Slim Digital Edition',
    descripcion: 'SSD de 1TB - 4K a 120fps - Ray tracing - Audio 3D Tempest',
    estado: 'nuevo',
    categoria: 'Consolas',
    marca: 'Sony',
    precio: 1899990,
    precioAnterior: 2199990,
    descuento: 14,
    calificacion: 4.9,
    envioRapido: true,
    vendedor: { id: 5, nombre: 'NVIDIA Store', reputacion: 4.9 },
    imagen: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=800'
  },
  {
    id: 32,
    nombre: 'Consola Xbox Series X 1TB',
    descripcion: '4K a 120fps - SSD de 1TB - Compatible con miles de juegos',
    estado: 'nuevo',
    categoria: 'Consolas',
    marca: 'Microsoft',
    precio: 1699990,
    calificacion: 4.8,
    envioRapido: true,
    vendedor: { id: 6, nombre: 'HP Store Oficial', reputacion: 4.5 },
    imagen: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?q=80&w=800'
  },
  {
    id: 33,
    nombre: 'Consola Nintendo Switch OLED',
    descripcion: 'Pantalla OLED de 7" - Modo portátil y dock - Joy-Con incluidos',
    estado: 'nuevo',
    categoria: 'Consolas',
    marca: 'Nintendo',
    precio: 999990,
    precioAnterior: 1099990,
    descuento: 9,
    calificacion: 4.8,
    envioRapido: true,
    vendedor: { id: 4, nombre: 'Luis Alejandro Montenegro Ojeda', reputacion: 4.7 },
    imagen: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?q=80&w=800'
  }
]


export const VENDEDORES = [
  {
    id: 1,
    nombre: 'LG Store Oficial',
    reputacion: 4.8,
    descripcion: 'Tienda oficial de LG en Colombia. Vendemos televisores y electrodomésticos con garantía de fábrica y envío a todo el país.',
    lugar: 'Bogotá, D.C.',
    fechaRegistro: '12/01/2024',
    usuarioForo: 'LGStoreOficial'
  },
  {
    id: 2,
    nombre: 'Lenovo Colombia',
    reputacion: 4.6,
    descripcion: 'Distribuidor autorizado de laptops y computadores Lenovo, con soporte técnico y garantía local en cada compra.',
    lugar: 'Medellín, Antioquia',
    fechaRegistro: '05/03/2024',
    usuarioForo: 'LenovoColombia'
  },
  {
    id: 3,
    nombre: 'Charlie Kirk',
    reputacion: 4.3,
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Charlie_Kirk_%2849271286182%29_%28cropped%29.jpg/960px-Charlie_Kirk_%2849271286182%29_%28cropped%29.jpg',
    descripcion: 'Venta de celulares y equipos Apple reacondicionados, con pruebas de funcionamiento y garantía por 3 meses.',
    lugar: 'Cali, Valle del Cauca',
    fechaRegistro: '18/09/2024',
    usuarioForo: 'CharlieKirk'
  },
  {
    id: 4,
    nombre: 'Luis Alejandro Montenegro Ojeda',
    reputacion: 4.7,
    descripcion: 'Vendedor particular de celulares Xiaomi. Respondo rápido por chat y hago entregas en Popayán y alrededores.',
    lugar: 'Popayán, Caucá',
    fechaRegistro: '30/04/2026',
    usuarioForo: 'Usuario AEGIS'
  },
  {
    id: 5,
    nombre: 'NVIDIA Store',
    reputacion: 4.9,
    descripcion: 'Tienda especializada en tarjetas gráficas y componentes PC de alto rendimiento para gaming y creación de contenido.',
    lugar: 'Barranquilla, Atlántico',
    fechaRegistro: '20/07/2024',
    usuarioForo: 'NVIDIAStore'
  },
  {
    id: 6,
    nombre: 'HP Store Oficial',
    reputacion: 4.5,
    descripcion: 'Tienda oficial de HP Colombia. Laptops, impresores y accesorios con garantía y soporte directo del fabricante.',
    lugar: 'Bogotá, D.C.',
    fechaRegistro: '02/11/2024',
    usuarioForo: 'HPColombia'
  },
  {
    id: 7,
    nombre: 'Samsung Store Oficial',
    reputacion: 4.7,
    descripcion: 'Tienda oficial de Samsung en Colombia. Televisores, celulares y electrodomésticos con garantía de fábrica y envío nacional.',
    lugar: 'Bucaramanga, Santander',
    fechaRegistro: '15/06/2024',
    usuarioForo: 'SamsungColombia'
  }
]

export function buscarVendedor(id) {
  if (id === undefined || id === null || id === '') return VENDEDORES[0]
  const encontrado = VENDEDORES.find((item) => String(item.id) === String(id))
  return encontrado || null
}


export function productosDelVendedor(vendedor) {
  const todos = [...PRODUCTOS_DESTACADOS, ...PRODUCTOS_PROMOCION, ...PRODUCTOS_PERFIL, ...PRODUCTOS_NOVEDADES]
  return todos.filter((item) => item.vendedor && vendedor && String(item.vendedor.id) === String(vendedor.id))
}


export function buscarProducto(id) {
  if (id === undefined || id === null || id === '') return PRODUCTOS_DESTACADOS[0]
  const todos = [...PRODUCTOS_DESTACADOS, ...PRODUCTOS_PROMOCION, ...PRODUCTOS_PERFIL, ...PRODUCTOS_NOVEDADES]
  const encontrado = todos.find((item) => String(item.id) === String(id))
  return encontrado || null
}
